# Generated by Django 4.0 on 2021-12-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
