# Generated by Django 4.0 on 2022-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant_meetup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date_published',
            field=models.DateField(auto_now=True),
        ),
    ]
