# Generated by Django 4.0 on 2022-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date_sent',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='2022-01-01', max_length=254),
            preserve_default=False,
        ),
    ]
