# Generated by Django 3.1.2 on 2021-12-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211226_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
