# Generated by Django 4.0 on 2022-01-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_emai',
            field=models.CharField(default='abc@gmail.com', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='dvhoa', max_length=120),
            preserve_default=False,
        ),
    ]
