# Generated by Django 4.0 on 2022-01-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_user_emai_comment_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_emai',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
    ]
